
skillMetadata:
  sections:
    - name: Settings
      fields:
        - name: search_engine
          type: text
          label: Favourite search engine
          value: "https://duckduckgo.com"
          placeholder: type URL of your favourite search engine
#    - name: Login << Name of another section
#      fields:
#        - type: label
#          label: Just a little bit of extra info for the user to understand following settings
#        - name: username
#          type: text
#          label: Username
#          value: ""
#        - name: password
#          type: password
#          label: Password
#          value: ""

